const SELECTED_BUSINESS_SCALE = 'SELECTED_BUSINESS_SCALE';
const SELECTED_JOB = 'SELECTED_JOB';
const SELECTED_RECRUIT_TYPE = 'SELECTED_RECRUIT_TYPE';
export const recruitFilterStorageKey = {
  SELECTED_BUSINESS_SCALE,
  SELECTED_JOB,
  SELECTED_RECRUIT_TYPE,
} as const;
